# This file enbles additional timer sensor for your dongle.
# Enable it via package include:
# packages:
#   timer: github://dentra/esphome-ewh/ewh-pkg-timer.yaml@$project_branch
# or if you like from local filesystem:
#   timer: !include ewh-pkg-timer.yaml
substitutions:
  time_platform: sntp

time:
  platform: $time_platform

text_sensor:
  - platform: template
    id: wh_timer
    name: Timer
    icon: mdi:timer-outline
    entity_category: diagnostic

ewh:
  on_state:
    then:
      - lambda: id(wh_timer).publish_state(str_snprintf("%02u:%02u", 5, state.timer_hours, state.timer_minutes));
      - lambda: id(wh_timer_hours).publish_state(str_snprintf("%02u", 2, state.timer_hours));
      - lambda: id(wh_timer_minutes).publish_state(str_snprintf("%02u", 2, state.timer_minutes));
